### PR TITLE
[geneus_main.py] suppress warning

### PR DESCRIPTION
**Pull request by furushchev**
To suppress errors like this:

```bash
Warnings << jsk_baxter_startup:symlink /home/travis/ros/ws_jsk_robot/logs/jsk_baxter_startup/build.symlink.000.log
Warning: Cannot symlink from /home/travis/ros/ws_jsk_robot/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/manifest.l to existing file /home/travis/ros/ws_jsk_robot/devel/share/roseus/ros/baxter_maintenance_msgs/manifest.l
Warning: Source hash: 58fe04e2e8539e5be98168e26638ee4d
Warning: Dest hash: a30d8e179f01bff293addfaa2f484218
Warning: Cannot symlink from /home/travis/ros/ws_jsk_robot/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_core_msgs/manifest.l to existing file /home/travis/ros/ws_jsk_robot/devel/share/roseus/ros/baxter_core_msgs/manifest.l
Warning: Source hash: 666b4d242a1d6795d4320ffadfd052ae
Warning: Dest hash: 707d28cf190a5fbf6aea616884b82abf
```

To merge this pull request:

- Pros
  - Never show the warning
  - depends written in `manifest.l` are in an alphabetical order
- Cons
  - Never written timestamp in `manifest.l` (still we can know by looking file created timestamp)

### CODE REVIEW

**Comment by k-okada** [comment]
> [geneus_main.py] do not write timestamp that makes different md5

I added timestamp because if msg is updated, then .l message is
automatically generated. Does this still works?




--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada 

> I added timestamp because if msg is updated, then .l message is
automatically generated.

Sorry, but I could not find actual part of this logic in any source codes nor any codes that use `THIS FILE IS AUTOMATICALLY GENERATED in ` line. Could you give me more detail?
I'd be happy if I can know where the part is, and critical situation that we can reproduce.

IMO, current `catkin_tools` generates all messages even if it is older or newer than one in `devel/share/roseus/ros`, and create symlinks to it, so I think it will not affect performance.

**Comment by furushchev** [comment]
@k-okada Any update?
I personally use this branch for 2 months and I don't think there is side effect on this change.

**Comment by k-okada** [comment]
done and released https://github.com/ros/rosdistro/pull/15020

**Comment by furushchev** [comment]
@k-okada Thanks! I believe this makes debug log more clear!

**Pull request merged**
