### PR TITLE
[geneus_main.py] Fix unexpected function responses caused by python gabage

### PR DESCRIPTION
**Pull request by wkentaro**
caused by python gc strategy

### CODE REVIEW

**Comment by wkentaro** [comment]
before
```
src [1]:
> from geneus.geneus_main import package_depends_impl

src [2]:
> len(package_depends_impl('geneus'))
> 2

src [3]:
> len(package_depends_impl('roseus'))
> 58

src [4]:
> len(package_depends_impl('geneus'))
> 58
```

**Comment by wkentaro** [comment]
src [1]:
> from geneus.geneus_main import package_depends_impl
WARNING: Package "ompl" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).

src [2]:
> len(package_depends_impl('geneus'))
> 1

src [3]:
> len(package_depends_impl('roseus'))
> 55

src [4]:
> len(package_depends_impl('geneus'))
> 1

**Comment by k-okada** [comment]
do we still need this?

**Comment by wkentaro** [comment]
I think so.
This is confusing when we test the function `test_depends_impl` from IPython.
(because the unexpected behavior only appears when `test_depends_impl` was called multiple times)

**Pull request merged**
