### PR TITLE
[geneus_main.py] fix pakcage_dpeneds, to solve https://github.com/start-jsk/2014-semi/issues/196 issue

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by k-okada** [comment]
@wkentaro, @furushchev , please check if this works for your demo program

**Comment by wkentaro** [comment]
I think I have same problem.
```
l1.irteusgl$ ros::load-ros-manifest "jsk_2014_picking_challenge"
/opt/ros/indigo/share/euslisp/jskeus/eus/Linux64/bin/irteusgl 0 error: no such package JSK_RECOGNITION_MSGS in (apply #'load-org-for-ros fullname args)
2.E1-ROS:irteusgl$ exit
```

**Comment by wkentaro** [comment]
https://gist.github.com/wkentaro/ae2dd0ab9220fdca1422

**Comment by k-okada** [comment]
can you tell which file cause the problem? last time I thought
jsk_recognitoin_msgs/manifest.l have two `(ros::ros-load-manifest
"jsk_recognition_msgs")`, and I think I fixed that.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
by cleaning ros workspace, It is solved.
I think the new geneus_main.py woks, and the problem I had above was because I had some packages which is not built again. sorry about that.

**Comment by k-okada** [comment]
thanks for confirming, it really help me.

**Comment by wkentaro** [comment]
Sorry, that was my misunderstandings, and I commented about that different issues.
This problem has not been solved yet.

**Comment by wkentaro** [comment]
I think this change solves this problem.
https://github.com/jsk-ros-pkg/geneus/pull/17

**Pull request merged**
