### PR TITLE
fix ros::load-ros-package order by dependencies

### PR DESCRIPTION
**Pull request by furushchev**
refered from https://github.com/jsk-ros-pkg/jsk_recognition/issues/701
I think it resolve the problem.

### CODE REVIEW

**Comment by k-okada** [comment]
does `reverse` solve this issue? on is this only solution for the problem?

--
◉ Kei Okada

**Comment by furushchev** [comment]
I think, the arg `ARG_MSG_DEPS` at the macro `_generate_eus` in `cmake/geneus-extras.cmake.em` is dep pkgs ordered by resolving dependencies and `ARG_MSG` is the package to be generated message.
Geneus is called like: `${GENEUS_BIN} ${ARG_MSG} (a.k.a args[1]) ${ARG_MSG_DEPS}(a.k.a arg[2:])`
so I think it's only way to do.
`

**Comment by k-okada** [comment]
ok, please write that explanation in the code

--
◉ Kei Okada

**Comment by k-okada** [comment]
ping

**Comment by k-okada** [comment]
can't wait ,please merge  https://github.com/furushchev/geneus/pulls

**Comment by furushchev** [comment]
I'm very sorry for the late response.
Now I merged.

**Comment by k-okada** [comment]
thanks!

**Pull request merged**
