### PR TITLE
[geneus/geneus_main.py] fix to use catkin_pkg.paackage to get only exec_depends]

### PR DESCRIPTION
**Pull request by k-okada**
@wkentaro, please check if this ok for you

### CODE REVIEW

**Comment by k-okada** [comment]
it may need something similar to #17

**Comment by wkentaro** [comment]
Okay, I can check this by tonight.

**Comment by wkentaro** [comment]
actually i dont understand **something similar**.

**Comment by wkentaro** [comment]
It raises 
```sh
$ python gen_eus.py geneus -m -o .
[WARNING] python-rospkg is not found in ROS_PACKAGE_PATH
Traceback (most recent call last):
  File "/home/wkentaro/semi/src/geneus/src/geneus/geneus_main.py", line 125, in genmain
    pkg_dependences = package_depends(pkg) + args[2:]   # args[1] ARG_PKG
  File "/home/wkentaro/semi/src/geneus/src/geneus/geneus_main.py", line 75, in package_depends
    for d in solve_depends_order(depends_impl):
  File "/home/wkentaro/semi/src/geneus/src/geneus/geneus_main.py", line 65, in solve_depends_order
    unsolved = filter(lambda x: x not in solved, rp.get_depends(d, False))
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 223, in get_depends
    m = self.get_manifest(name)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 163, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 207, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 199, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: python-rospkg
```

**Comment by wkentaro** [comment]
in the first place, should we see only `<run_depends>` not `<build_depends>`?

**Comment by wkentaro** [comment]
I thought message files are generated while building, so `<build_depend>` is apropriate.

**Comment by k-okada** [comment]
```
k-okada@kokada-t440s:~/ros/indigo_parent/src/geneus$ ./scripts/gen_eus.py
geneus -m -o .
WARNING: Package "ompl" does not follow the version conventions. It should
not contain leading zeros (unless the number is 0).
k-okada@kokada-t440s:~/ros/indigo_parent/src/geneus$ git branch
  add_executable
  const_to_symbol
  fix_depend3
* fix_depend4
  fix_depends2
  fix_get_depends
  master
```

i have different output and yes, we'd see only run_depends, because when
you install package A as deb package, then apt-get did not install package
B which is only build depend to A

--
◉ Kei Okada

**Comment by wkentaro** [comment]
fix_depend4
does not raise such error. 
But manifest.l generated by 
```
$ ./script/gen_eus.py jsk_2014_picking_challenge -m -o .
```
does not contains jsk_recognition_msgs as dependencies.
```
;;
;; DO NOT EDIT THIS FILE
;;
(ros::load-ros-package "rosserial_arduino")
(ros::load-ros-package "sound_play")
(ros::load-ros-package "std_msgs")
(ros::load-ros-package "actionlib_msgs")
(ros::load-ros-package "actionlib")
(ros::load-ros-package "dynamic_reconfigure")
(ros::load-ros-package "geometry_msgs")
(ros::load-ros-package "jsk_interactive_marker")
(ros::load-ros-package "posedetection_msgs")
(ros::load-ros-package "jsk_2014_picking_challenge")
```

**Comment by k-okada** [comment]
do you have jsk_visualization package in you workspace? if you use jsk_visualization under /opt/ros/indigo, then manifest.l for these package is generated by old geneus

**Comment by wkentaro** [comment]
Yes, I have jsk_visualization in my workspace.

**Comment by k-okada** [comment]
Please try after removing deb packages of jsk_visualization

--
◉ Kei Okada

2015/04/18 18:50、Kentaro Wada <notifications@github.com> のメッセージ:

**Comment by wkentaro** [comment]
It is not solved.

**Comment by k-okada** [comment]
Humm, it solved in my environment, did you solve this in #18 ? which manifest.xml is different.

**Comment by wkentaro** [comment]
Yes it is solved in #18 .
What is manifest.xml?

**Comment by wkentaro** [comment]
Just for confirmation, did you mean remove ros packages installed from `apt-get` in
> Please try after removing deb packages of jsk_visualization
specifically, like below?
```
$ sudo aptitude remove ros-indigo-jsk-rviz-plugins ros-indigo-interactive-marker ...
```

**Comment by wkentaro** [comment]
There is no `(ros::load-ros-package "jsk_recognition_msgs")` in the `manifest.l` which is generated by `geneus` in #20 .

**Comment by k-okada** [comment]
manifest.xml -> manifest.l

And what is difference between  #18 and #20

2015年4月19日日曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> Yes it is solved in #18 <https://github.com/jsk-ros-pkg/geneus/pull/18> .
> What is manifest.xml?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/geneus/pull/20#issuecomment-94248714>.
>


-- 
--
◉ Kei Okada

**Comment by k-okada** [comment]
Yes

2015年4月19日日曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> Just for confirmation, did you mean remove ros packages installed from
> apt-get in
>
> Please try after removing deb packages of jsk_visualization
> specifically, like below?
>
> $ sudo aptitude remove ros-indigo-jsk-rviz-plugins ros-indigo-interactive-marker ...
>
>  —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/geneus/pull/20#issuecomment-94248824>.
>


-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
> And what is difference between  #18 and #20 

I think the packages included in manifest.l is same.
in #18, I rearrange package dependencies to avoid not found error in `manifest.l`.

**Comment by wkentaro** [comment]
Both #18 and #20 finds dependencies from `run_depend` in `package.xml`.
I used same codes in #18 as #20 to get dependencies.

**Comment by k-okada** [comment]
but you said #18 works and #20 did not. Is it correct? should we merge #18,
I think #20 is better because it can get rid of old RosPack() interface.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
The difference between #18 and #20 is just the rearrangement (https://github.com/jsk-ros-pkg/geneus/pull/18/files#diff-3b84e240f81b3651ac8336f3a5a15846R67) and etc.
#20 does not work because it does not catch error like (https://github.com/jsk-ros-pkg/geneus/pull/18/files#diff-3b84e240f81b3651ac8336f3a5a15846R60) .

And also in #20 RosPack() is used here (https://github.com/jsk-ros-pkg/geneus/pull/20/files#diff-3b84e240f81b3651ac8336f3a5a15846R57) .

**Comment by wkentaro** [comment]
Do you mean #21 as code which does not use RosPack() ?

**Comment by k-okada** [comment]
yes, #21, not #20

--
◉ Kei Okada

**Comment by k-okada** [comment]
> not work because it does not catch error like (
https://github.com/jsk-ros-pkg/geneus/pull/18/files#diff-3b84e240f81b3651ac8336f3a5a15846R60)
.
As far as I understand correctly, this happens if you have system
dependency in `depends[]` and that is avoided by using package_list here
https://github.com/jsk-ros-pkg/geneus/pull/21/files#diff-3b84e240f81b3651ac8336f3a5a15846R79

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Actually, I don't know why the dependencies generated by #21 is so few.

**Comment by wkentaro** [comment]
I sent another commit to #18 .
https://github.com/wkentaro/geneus/commit/839c49dccd92d7f75c8c05c7c7674414fa9f3dd2

It does not use rospkg but catkin.

**Comment by k-okada** [comment]
closed via #18

**Pull request closed without merging**
