### PR TITLE
[geneus] treat uint8[] as string like rospy

### PR DESCRIPTION
**Pull request by furushchev**
This is claimed at https://github.com/jsk-ros-pkg/geneus/issues/14
Until merging this change, existing codes that treats messages containing `uint8[]` will fail.(e.g.: converting `sensor_msgs/PointCloud2` to eus-pointcloud)

### CODE REVIEW

**Comment by garaemon** [comment]
Does it mean we need to modify existing code?

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_demos/blob/master/jsk_2015_06_hrp_drc/drc_com_common/msg/FC2OCSBasicInfoSmall.msg

**Comment by k-okada** [comment]
it depends on what kind of code you write, where is the code that uses FC2OCSBasicInfoSmall.msg?
Before i rewrite geneus, uint8[] is convert to `string`, and at here https://github.com/jsk-ros-pkg/geneus/commit/b157cd5fb0abfd4a0c422fa9b78e5d379cc0ef2f, I have change them to` integer-vector` but that may not correct. at least it fails at https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/roseus_c_util.c#L50

**Comment by garaemon** [comment]
Hmm, I'm treating elements of `uint8[]` as integer.

This is another example:
* message https://github.com/jsk-ros-pkg/jsk_demos/blob/master/jsk_2015_06_hrp_drc/drc_com_common/msg/HumanoidJointAngles.msg
* code https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_network_tools/euslisp/joint-state-decompressor.l#L48

**Comment by garaemon** [comment]
`(elt <string> <index>)` returns character constant and it may be no problem.

**Comment by k-okada** [comment]
humm, if we convert uint to integer-vector
- check integer-vector, not string in roseus_c_utils.c 
- previous string implementation is very efficient because we do not run dolist, but memcpy to fill the data in deserialize phase, can we use that technique to integer-vector?

**Comment by garaemon** [comment]
Could you test `roslaunch jsk_network_tools joint_state_compress_sample.launch Y_DIFF=1.0` before merging this?

If it work, I'm willing to accept this change.

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_common/pull/852

This pull request may be required to run that.

**Comment by k-okada** [comment]
ok, please check this @furushchev

**Comment by furushchev** [comment]
I tried to test `joint_state_compress_sample.launch`, and looked rviz, but the poses of robots("no TF prefix" and with "decompressed") are quite different each other.(I use PR2 on local)
Is this correct? If correct, how can I test?

**Comment by furushchev** [comment]
Poses are different both on normal geneus environment and "this pullreq" geneus environment.

**Comment by garaemon** [comment]
It should be almost same

2015年4月9日木曜日、Furushchev<notifications@github.com>さんは書きました:

> Poses are different both on normal geneus environment and "this pullreq"
> geneus environment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/geneus/pull/15#issuecomment-91231111>.
>


-- 
✉︎ from iPhone

**Comment by furushchev** [comment]
@garaemon I added test for angle vector compress/decompress https://github.com/jsk-ros-pkg/jsk_common/pull/856.
I'll now check if occurs any problem using this test.

**Comment by furushchev** [comment]
I checked error in both env:

- norm of difference between raw and decompressed angle-vector
  - 1.50817 (normal geneus env)
  - 1.50817 (new geneus env)

- norm of difference between raw and decompressed angle-vector

in existing geneus env:

```
head_tilt_joint: 0.000615
head_pan_joint: -0.003425
r_wrist_roll_joint: 0.002261
r_wrist_flex_joint: 0.005686
r_forearm_roll_joint: -0.003865
r_elbow_flex_joint: 6.28319
r_upper_arm_roll_joint: 0.003725
r_shoulder_lift_joint: 6.28319
r_shoulder_pan_joint: 0.003425
l_wrist_roll_joint: 0.002261
l_wrist_flex_joint: -0.005686
l_forearm_roll_joint: -0.003865
l_elbow_flex_joint: 6.28319
l_upper_arm_roll_joint: 0.003725
l_shoulder_lift_joint: 6.28319
l_shoulder_pan_joint: 0.011204
torso_lift_joint: 0.001526
(norm diff): 12.5664
```

- in new geneus env:

```
head_tilt_joint: -0.13585
head_pan_joint: -0.564602
r_wrist_roll_joint: -0.3536
r_wrist_flex_joint: -0.65
r_forearm_roll_joint: 0.003865
r_elbow_flex_joint: 1.30592
r_upper_arm_roll_joint: -0.540196
r_shoulder_lift_joint: 0.936318
r_shoulder_pan_joint: -0.790692
l_wrist_roll_joint: 1.2963
l_wrist_flex_joint: -1.54137
l_forearm_roll_joint: 0.98565
l_elbow_flex_joint: 4.97727
l_upper_arm_roll_joint: -0.540196
l_shoulder_lift_joint: 5.34687
l_shoulder_pan_joint: -0.011204
torso_lift_joint: 1.29626
(norm diff): 8.04649
```

the difference of joint_states are bigger in existing environment than new environment.

**Comment by furushchev** [comment]
I got it, lift_joint are rotational joint? (2 * pi different?)
Anyway there is the difference among enviromnents... What should I do...

**Comment by garaemon** [comment]
`lift_joint` problem should be resolved already.
https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_network_tools/euslisp/angle-vector-compress.l#L9

**Comment by garaemon** [comment]
I will confirm this patch and please wait to merge this

2015年4月11日土曜日、Furushchev<notifications@github.com>さんは書きました:

> I got it, lift_joint are rotational joint? (2 * pi different?)
> Anyway there is the difference among enviromnents... What should I do...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/geneus/pull/15#issuecomment-91831672>.
>


-- 
✉︎ from iPhone

**Comment by furushchev** [comment]
The problem is two:
- `lift_joint` error is `2 * pi` above when (de)compressed
- (de)serialization of uint8[n] (fixed length) does not work by new `geneus` change

I fixed and updated new `geneus` pullreq and now I think it's ok (all geneus test passed and `joint_state_compressor` returns the same values as on existing `geneus` environment.)

**Comment by furushchev** [comment]
NOTE: Still please do not merge before the test ( https://github.com/jsk-ros-pkg/jsk_roseus/pull/269 ) passes.

**Comment by furushchev** [comment]
Sorry I mistook comment.
At first please merge this for testing `message.l` generated by new `geneus`:
- jsk-ros-pkg/jsk_roseus#269
- https://github.com/jsk-ros-pkg/jsk_common/pull/856

**Pull request merged**
