### PR TITLE
[generate.py] add feature to write const to string

### PR DESCRIPTION
**Pull request by k-okada**
see https://github.com/start-jsk/rtmros_common/pull/687 for discussion, -to-symbol ? -to-string ?

### CODE REVIEW

**Comment by snozawa** [comment]
> see start-jsk/rtmros_common#687 for discussion, -to-symbol ? -to-string ?

Hmm, it is difficult problem, but currently I'm +1 for `-to-string`.
This is because we cannot consider case sensitivity by using symbol, such as `Hoge` and `hoge`.

When we want to convert non-Euslisp program to Euslisp program, 
it would be better to use string instead of symbol 
because non-Euslisp program consider both upper case and down case and we need to keep consistency.

**Comment by k-okada** [comment]
do you mean we should return "string"? or we can return symbol but the 
function name is -string ?

--
◉ Kei Okada

**Comment by snozawa** [comment]
I meant we should return "string".

**Comment by k-okada** [comment]
I see,  it is true that symbol can not distinguish "Pending" and "PENDING"
but also think using string may require more careful about programming and
I never see constant using lower letter for constant. If we can assume all
constant name is CAPTITAL letter, the problem becams very simple. Asked in
https://github.com/ros/genmsg/issues/58

--
◉ Kei Okada

**Pull request merged**
