### PR TITLE
[geneus_main.py] Resolve package dependencies with attention to the order

### PR DESCRIPTION
**Pull request by wkentaro**
After #17

### CODE REVIEW

**Comment by k-okada** [comment]
ok, restarted travis to pass the test.

**Comment by wkentaro** [comment]
It fails because of this line. 
https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/test/test-genmsg.sh#L349

`catkin config` does not have `--no-jobserver` option.

**Comment by wkentaro** [comment]
So we should fix it first.

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_roseus/pull/271 may solve this
2015年4月14日火曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> So we should fix it first.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/geneus/pull/18#issuecomment-92835925>.
>


-- 
--
◉ Kei Okada

**Comment by k-okada** [comment]
can you rebase origin/master?

**Comment by wkentaro** [comment]
I rebased it.

**Comment by wkentaro** [comment]
In my env using latest jsk_roseus which is installed from github, the test passes.
The travis test downloads latest test scripts, but does not download other scripts.
Are there any dependencies on test-genmsg.sh or generate-all-msg-srv.sh which should be latest version?

**Comment by wkentaro** [comment]
I think the test failure is because of this line.
https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/test/test-genmsg.sh#L81

This means `geneus_dep1` depends on roseus, right?
and `roseus` depends on `angles` but there is no `angles` package in the test environment. That's why this travis test fails.

**Comment by wkentaro** [comment]
I committed temporary one for travis test.
https://github.com/jsk-ros-pkg/geneus/commit/4612ef0b1bc90cca480a5e38fd959e26952ed4e3
So **DON'T MERGE THIS**

**Comment by k-okada** [comment]
by the way, it there any reason that you did not use implicit depends?

**Comment by wkentaro** [comment]
What line are you pointing at?

2015年4月17日金曜日、Kei Okada<notifications@github.com>さんは書きました:

> by the way, it there any reason that you did not use implicit depends?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/geneus/pull/18#issuecomment-93868498>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
this is my misunderstanding
https://github.com/jsk-ros-pkg/geneus/pull/18/files#diff-3b84e240f81b3651ac8336f3a5a15846R79

you also use implicit for get_depends.

https://github.com/ros-infrastructure/rospkg/blob/8f8e160dc8df8a9178091294cd91a9607f6fad67/src/rospkg/rospack.py#L210

thnaks

**Comment by k-okada** [comment]
Humm,
you use get_depends(True) at 
https://github.com/jsk-ros-pkg/geneus/pull/18/files#diff-3b84e240f81b3651ac8336f3a5a15846R75
and this try to find build depends, can we use get_depends(Flase) ?

**Comment by wkentaro** [comment]
Okay I chaned it.

**Comment by k-okada** [comment]
humm, still try to find angles (buidl_depend)

```
[WARNING] cmake_modules is not found in ROS_PACKAGE_PATH 
[WARNING] mk is not found in ROS_PACKAGE_PATH 
Traceback (most recent call last): 
  File "/home/travis/ros/ws_geneus/src/geneus/src/geneus/geneus_main.py", line 120, in genmain 
    pkg_dependences = package_depends(pkg) + args[2:]   # args[1] ARG_PKG 
  File "/home/travis/ros/ws_geneus/src/geneus/src/geneus/geneus_main.py", line 71, in package_depends 
    for d in solve_order_of_depends(depends_impl): 
  File "/home/travis/ros/ws_geneus/src/geneus/src/geneus/geneus_main.py", line 61, in solve_order_of_depends 
    unsolved = filter(lambda x: x not in solved, rp.get_depends(d, False)) 
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 223, in get_depends 
    m = self.get_manifest(name) 
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 163, in get_manifest 
    return self._load_manifest(name) 
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 207, in _load_manifest 
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self) 
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 199, in get_path 
    raise ResourceNotFound(name, ros_paths=self._ros_paths) 
ResourceNotFound: angles 
ROS path [0]=/opt/ros/hydro/share/ros 
ROS path [1]=/tmp/test_genmsg_18470/src/geneus_dep1 
ROS path [2]=/home/travis/ros/ws_geneus/src/geneus 
ROS path [3]=/opt/ros/hydro/share 
ROS path [4]=/opt/ros/hydro/stacks
```

**Comment by wkentaro** [comment]
I changed to see only run_depend in package.xml referring to #20.

**Comment by k-okada** [comment]
very nice, hopefully this is the last question, what is the difference between ros_depends and tmp_depends

**Comment by wkentaro** [comment]
ros_depends are dependencies which all are ROS packages.

get_depends() collects package dependencies from package.xml so it contains non ros packages. (in other words it removes python packages in many cases)
https://github.com/jsk-ros-pkg/geneus/pull/18/files#diff-3b84e240f81b3651ac8336f3a5a15846R103

tmp_depends are dependencies which are not included by depends (which is arg in recursive function).
by filtering [here](https://github.com/jsk-ros-pkg/geneus/pull/18/files#diff-3b84e240f81b3651ac8336f3a5a15846R103), tmp_depends only includes ROS packages.

**Comment by k-okada** [comment]
ok, so can we merge this one?

**Comment by wkentaro** [comment]
I think this does work, please merge this.

**Comment by k-okada** [comment]
This will close #21, close #20 ,close #24

**Pull request merged**
